### ISSUE TITLE
Vim Script 'magic number' for stripping causes issue with single width icons

### ISSUE THREAD

**Issue by coreyja** [coreyja/devicon-lookup#2]
As pointed out by @mellery451 for some file types (ie: `txt`) the icons are single width, not double width characters. This causes issue when the VIM script tries to scrip them away using my magic number approach.

**Comment by coreyja** [comment]
@mellery451 as a workaround for the normal version (NOT the git diff one) you can probably change the `s:edit_devicon_prepended_file` function to the following body that I took from @dkarter's comment here https://github.com/ryanoasis/vim-devicons/issues/106#issuecomment-354629715

```
    let l:pos = stridx(a:item, ' ')
    let l:file_path = a:item[pos+1:-1]
    execute 'silent e' l:file_path
```

That looks for a space ` ` and uses that instead of my magic number approach! I knew that magic number was gonna come back to bite me 🤣 

The reason I diverged from that code snippet is for the git diff view, where I needed to strip an unknown number of spaces. But it should work great for the standard version!

**Comment by mellery451** [comment]
@coreyja - that change works - thanks!

**Comment by ri-aje** [comment]
@coreyja hi for `txt` file failure, isn't that because you used a plain `e` in your source? https://github.com/coreyja/devicon-lookup/blob/c00c78f35f7a0880460cb47d6a05281b670f03b9/src/main.rs#L103
that looks like a bug and should be fixed instead of needing a workaround. all other map items use some icons other than ascii chars. for `txt` files, it should just use the default icon, right?

**Comment by coreyja** [comment]
Sorry for the delayed response!

> that looks like a bug and should be fixed instead of needing a workaround

Correct! That is why there is still an issue open on the repo!

> it should just use the default icon, right?

Most likely but I haven't put a ton of thought into it! Maybe there is a better icon to use instead of the default? I haven't looked though so I do not know!

@ri-aje If you are willing to make a Pull Request I would happily review it and get it merged in!

**Comment by coreyja** [comment]
@ri-aje 
I used Cargo so to build I have been using `cargo build` and i've been running it with `cargo run`

As a simple test case I've been doing `ls | cargo run`

**Comment by ri-aje** [comment]
@coreyja sent https://github.com/coreyja/devicon-lookup/pull/3. seem cannot add you as reviewer, so letting you know here.

**Comment by coreyja** [comment]
@ri-aje was gracious enough to fix the issue with the character for `e`! So this should no longer be an issue, as I believe the rest of the current characters are double width!

I still want to leave this issue open, as I think I want to fold the VIM script into the repo, and then I think I want to iterate on the 'magic number' solution.

Thanks again to @ri-aje for getting the `txt` icon switched out! 👏

**Comment by ri-aje** [comment]
@coreyja happy to make a contribution.

**Comment by coreyja** [comment]
I've moved the `vim` specific implementation details over to [fzf.devicon.vim](https://github.com/coreyja/fzf.devicon.vim/) and I believe that it also solves this issue! Please give that plugin a try and report any VIM specific issues on that repo if you have any.

Thanks everyone!
